schedules:
- cron: '0 18 * * *'
  displayName: Daily midnight deletion
  branches:
    include:
    - main

stages:
  - stage: 'DestroyTerraform'
    jobs:
    - job: destroyTerraform
      steps:
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'OS_fra_connection'
          backendAzureRmResourceGroupName: 'company'
          backendAzureRmStorageAccountName: 'companystorage'
          backendAzureRmContainerName: 'companycontainer'
          backendAzureRmKey: 'companydev.terraform.tfstate'
          
      - task: TerraformTaskV4@4
        displayName: 'Terraform Destroy'
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          environmentServiceNameAzureRM: 'OS_fra_connection'

      - task: AzurePowerShell@5
        displayName: 'Delete AzureDevops Agent'
        inputs:
          azureSubscription: 'OS_fra_connection'
          azurePowerShellVersion: LatestVersion
          ScriptType: 'InlineScript'
          inline: |

            $PAT = "26swzs7bmqaw2ae26vy5ouyc7nedqpn2ix7rnltsscknqy7dd3pa"
            $OrganizationName = "OS-company-Dev"
            $AgentPoolName = "Default"
            $ApiVersion = '5.1'

            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            $EncodedPAT = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":$PAT"))
            $PoolsUrl = "https://dev.azure.com/$($OrganizationName)/_apis/distributedtask/pools?api-version=$($ApiVersion)"
            try {
            $Pools = (Invoke-RestMethod -Uri $PoolsUrl -Method 'Get' -Headers @{Authorization = "Basic $EncodedPAT"}).value
            } catch {
            throw $_.Exception
            }

            If ($Pools) {
            $PoolId = ($Pools | Where-Object { $_.Name -eq $AgentPoolName }).id
            $AgentsUrl = "https://dev.azure.com/$($OrganizationName)/_apis/distributedtask/pools/$($PoolId)/agents?api-version=$($ApiVersion)"
            $Agents = (Invoke-RestMethod -Uri $AgentsUrl -Method 'Get' -Headers @{Authorization = "Basic $EncodedPAT"}).value
            if ($Agents) {
              $AgentNames = ($Agents | Where-Object { $_.status -eq 'Offline'}).Name
              $OfflineAgents = ($Agents | Where-Object { $_.status -eq 'Offline'}).id
              foreach ($OfflineAgent in $OfflineAgents) {
                foreach ($AgentName in $AgentNames) {
                  Write-Output "Removing: $($AgentName) From Pool: $($AgentPoolName) in Organization: $($OrganizationName)"
                  $OfflineAgentsUrl = "https://dev.azure.com/$($OrganizationName)/_apis/distributedtask/pools/$($PoolId)/agents/$($OfflineAgent)?api-version=$($ApiVersion)"
                  Invoke-RestMethod -Uri $OfflineAgentsUrl -Method 'Delete' -Headers @{Authorization = "Basic $EncodedPAT"}
                }
              }
            } else {
              Write-Output "No Agents found in $($AgentPoolName) for Organization $($OrganizationName)"
            }
            } else {
            Write-Output "No Pools named $($AgentPoolName) found in Organization $($OrganizationName)"
            }
